name    'narkisr-jdk'
version '0.0.1'
source 'git://github.com/narkisr/puppet-jdk.git'
author 'Ronen Narkis <narkisr@gmail.com>'
license 'Apache 2.0'
summary 'Install oracle jdk 6 on both Centos and Ubuntu'
description 'Install oracle jdk 6 on both Centos and Ubuntu'
project_page 'https://github.com/narkisr/puppet-jdk'

dependency 'puppetlabs/stdlib', '>= 2.0.0'
dependency 'puppetlabs/apt', '>= 2.0.0'
